# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "nafergo's weekly report"
email: nafergo@gmail.com
description: "Weekly log of nafergo's work for [PAV](https://www.poloarqueviseu.pt/) (Polo Arqueológico de Viseu, portuguese for Viseu Archaeology Centre)"
baseurl: "/weekly-report" # the subpath of your site, e.g. /blog
url: "https://nafergo.github.io" # the base hostname & protocol for your site
twitter_username: nafergo
github_username:  nafergo
paginate: 5

plugins: [jekyll-paginate, kramdown]

# Build settings
markdown: kramdown
